version: 0.0 
os: linux 
files:
  - source: helloworld.js
    destination: /usr/local/helloworld/
  - source: scripts/HelloWorld.service
    destination: /etc/systemd/system/
  - source: scripts/HelloWorld.sh
      destination: /home/ec2-user/


hooks: 
  BeforeInstall: 
    - location: scripts/stop.sh 
      timeout: 30 
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 30
  ValidateService:
    - location: scripts/validate.sh
